services:

  postgres:
    image: postgres:16
    container_name: postgres_helpdesk
    restart: always

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - "${POSTGRES_PORT}:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer_helpdesk
    restart: always

    ports:
      - "${ADMINER_PORT}:8080"

  n8n:
    image: n8nio/n8n
    container_name: n8n_helpdesk
    restart: always

    ports:
      - "${N8N_PORT}:5678"

    environment:
      - TZ=${TZ}

    volumes:
      - ./n8n_data:/home/node/.n8n
      - ./input:/files/input
      - ./output:/files/output
      - ./logs:/files/logs

volumes:
  postgres_data: